- name: install multi packages using loops
  hosts: web
  become: yes
  tasks:
  - name: install mysql, nginix and postfix
    ansible.builtin.packages:
      name: '{{ item }}'
      state: '{{ item }}'
    loop:
    - mysql
    - nginx
    - postfix