- name: install multi packages using loops
  hosts: web
  become: yes
  tasks:
  - name: install mysql, nginix and postfix
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix